### ISSUE TITLE
Colon symbol in address name

### ISSUE THREAD

**Issue by aliismayilov** [email-spec/email-spec#144]
```ruby
let!(:mail) { IssueNotifierMailer.digest }

it { expect(mail).to deliver_from("HE:tech <tech@example.com>") }
```

Our company has a colon in its name. Sending from ```HE:tech <tech@example.com>``` does not create any problems. But when I try to test it with ```expect(mail).to deliver_from("HE:tech <tech@example.com>")``` I receive following error:
```
Failure/Error: it { expect(mail).to deliver_from("HE:tech <tech@example.com>") }
Mail::Field::ParseError:
  Mail::AddressListsParser can not parse |HE:tech <tech@example.com>|
  Reason was: Expected one of
  , (, ,, ; at line 1, column 29 (byte 29) after :tech <tech@example.com>
```

**Comment by schmierkov** [comment]
All non-standard characters need to be in quotes according to RFC822.
The email mentioned should be something like `"HE:tech" <tech@example.com>`

I'm closing this issue, thanks.
