### ISSUE TITLE
Explicit RSpec reference in email_spec/helpers.rb

### ISSUE THREAD

**Issue by Patru** [email-spec/email-spec#158]
I am writing an application based on Cuba which I am testing with Minitest. I want to use Pony for sending E-Mails so I thought email_spec would be a good candidate for testing. 

I tried to write my first failing test with email_spec so I tried to open an E-Mail I had not written yet. My call to ```open_last_email_for``` was answered with an

    Minitest::UnexpectedError: NameError: uninitialized constant EmailSpec::Helpers::RSpec
         /Users/.../vendor/bundle/gems/email_spec-1.6.0/lib/email_spec/helpers.rb:46:in `current_email'

Checking out this line I found 

    raise   RSpec::Expectations::ExpectationNotMetError, "Expected an open email but none was found. Did you forget to call open_email?" unless email

an RSpec reference that my Gemfile would obviously not satisfy as I only wanted to use Minitest.

Shouldn't we have an ```EmailSpec:: ``` error which can achieve the same effect?

Also I am weary to hit similar problems when I indirectly call

    RSpec::Expectations::PositiveExpectationHandler.handle_matcher(email, matcher)

in ```parse_email_for_link``` when I try to finally click my link.

**Comment by mauro-oto** [comment]
I think this has been fixed by https://github.com/myobie/email-spec/commit/5c425c5addcaf7fe12a211f56b0ef8d60ca831be

**Comment by etagwerker** [comment]
@mauro-oto You're right. @Patru This is now fixed.
