### ISSUE TITLE
Please cut a release....

### ISSUE THREAD

**Issue by ronaldsalas** [email-spec/email-spec#164]
Hi, it's been a while since the new update and hope a new version of the gem can be released soon..

**Comment by etagwerker** [comment]
@ronaldsalas Here it is! https://rubygems.org/gems/email_spec/versions/2.0.0 - https://github.com/email-spec/email-spec/blob/master/History.txt#L1

**Comment by ronaldsalas** [comment]
@etagwerker awesome! thanks!!
