### ISSUE TITLE
Deprecation Warning using RSpec 3.0.2

### ISSUE THREAD

**Issue by xirukitepe** [email-spec/email-spec#166]
Hi, can someone please help me resolve this warning message?

        --------------------------------------------------------------------------------
        EmailSpec::Matchers::HaveSubject implements a legacy RSpec matcher
        protocol. For the current protocol you should expose the failure messages
        via the `failure_message` and `failure_message_when_negated` methods.
        (Used from /home/xiruki/Work/serviceseeking/spec/mailers/provider_account_mailer_spec.rb:29:in `block (3 levels) in <top (required)>')
        --------------------------------------------------------------------------------

        If you need more of the backtrace for any of these deprecations to
        identify where to make the necessary changes, you can configure
        `config.raise_errors_for_deprecations!`, and it will turn the
        deprecation warnings into errors, giving you the full backtrace.

        4 deprecation warnings total

        Finished in 15.36 seconds (files took 3 minutes 53.9 seconds to load)

I've tried updating to latest commit from this branch, but I'm getting gem dependencies error(s).

**Comment by schmierkov** [comment]
Hi @xirukitepe, could you provide a code example in your `provider_account_mailer_spec.rb` and the current email-rspec gem versions you are using? Thanks

**Comment by etagwerker** [comment]
@xirukitepe Try upgrading to the latest version of `email-spec`

We have an example rails root folder in the project which is now using the latest version of `rspec` and it's not raising any deprecation warnings. See: https://github.com/email-spec/email-spec/blob/master/examples/rails4_root/Gemfile
