### ISSUE TITLE
mail.html method useful?

### ISSUE THREAD

**Issue by eliotsykes** [email-spec/email-spec#173]
This monkey patch is being used on a project to add a `#html` method to `Mail::Message`:

```ruby
module EmailSpec::MailExt
  def html
    html_part.body.to_s
  end
end
```
This helps when using capybara matchers within mailer specs like `have_css`:

```ruby
expect(mail.html).to have_css 'p', 'Welcome to our site'
```

Would a PR be of interest that included the `#html` method and associated tests?

**Comment by etagwerker** [comment]
@eliotsykes Yes, that would be welcomed.

**Comment by eliotsykes** [comment]
Ah fantastic. Thanks for the quick response and wonderful gem @etagwerker ! I will submit a PR in the next few days.
