### ISSUE TITLE
Testing in isolation seems to fail

### ISSUE THREAD

**Issue by pedrofoliveira** [email-spec/email-spec#176]
Running the following test (resembling the given example):
```  
 it "tests the contact email controller" do
      expect(ContactMailer).to receive(:contact_email)
      post '/send_contact', contact: { email: "email@example.com", name: "Jimmy Bean", subject: "This is the subject", content: "This is the message body" }
    end
```

fails with:
Failure/Error: ContactMailer.contact_email(@name, @email, @subject, @content).deliver_now
     
     NoMethodError:
       undefined method `deliver_now' for nil:NilClass

The included examples don't seem to isolate the controller test from the mail test!!

Using:
Rails: 4.2.5.1
email_spec: 2.0.0

**Comment by etagwerker** [comment]
@pedrofoliveira This is not an `email_spec` issue. Please correct your code. 

`expect(ContactMailer).to receive(:contact_email)` makes `ContactMailer.contact_email` return `nil`

You probably want to do this: 

```
 it "tests the contact email controller" do
      expect(ContactMailer).to receive(:contact_email).and_call_original
      post '/send_contact', contact: { email: "email@example.com", name: "Jimmy Bean", subject: "This is the subject", content: "This is the message body" }
end
```
