### ISSUE TITLE
Match have body text with special characters

### ISSUE THREAD

**Issue by IlkhamGaysin** [email-spec/email-spec#182]
If in my factory user full name generate like ('Jermain O'Keefe') rspec test will be fall with follow message: 

``expected the body to contain "Jermain O'Keefe" but was "<p>Jermain O&#39;Keefe!</p>``

Rspec story:
```
feature "Send notification" do
  subject { NotifyMailer.send_notify(user) }

  scenario "User gets notification" do
    expect(subject).to have_body_text(user.full_name)
  end
end
```

**Comment by mauro-oto** [comment]
Closed by https://github.com/email-spec/email-spec/pull/183
