### ISSUE TITLE
Documentation for how to configure email_spec

### ISSUE THREAD

**Issue by snoblenet** [email-spec/email-spec#20]
If you had the time to add documentation for how to configure email_spec, that would be grand.

Pony is sending mail, but email_spec isn't seeing it, probably because I've not configured it correctly.

In particular, further detail about how to configure current_email_address would be useful.

Thank you.

**Comment by etagwerker** [comment]
@snoblenet The documentation has evolved since this issue was reported. Please let me know if it's still not clear. Thanks!
