### ISSUE TITLE
Update to support mail gem 2.7

### ISSUE THREAD

**Issue by stereobooster** [email-spec/email-spec#200]
Well mail gem 2.7 is not released yet, but there is release candidate. Let this ticket be here until they release. Can not wait it, because it use `mini_mime` instead of `mime-types`, which shaves of ~4mb of memory.

**Comment by stereobooster** [comment]
Or maybe create RC version of this gem, which will use RC version of mail gem. I can do PR

**Comment by etagwerker** [comment]
@stereobooster That's a great idea. Please open a PR with the new dependency. Thanks!
