### ISSUE TITLE
New gem version

### ISSUE THREAD

**Issue by pedantic-git** [email-spec/email-spec#206]
Hi maintainers 

Sorry for raising an issue about this. My PR #192 was merged way back in July but there hasn't been a new version of this gem published to rubygems since then. Is there any chance of a release in the near future?

Thanks!!

**Comment by etagwerker** [comment]
@pedantic-git Done. Thanks for your contribution! 

PR #192 is now published here: https://rubygems.org/gems/email_spec/versions/2.2.0

**Comment by pedantic-git** [comment]
Fantastic! Thanks!
