### ISSUE TITLE
2.2.1 gem released but master is 2.2.0

### ISSUE THREAD

**Issue by Whitespace** [email-spec/email-spec#222]
A new version was pushed by @etagwerker but there's no `v2.2.1` tag or any reference in the Changelog.

`lib/email_spec/version.rb` remains at `2.2.0`

CF: https://rubygems.org/gems/email_spec/versions/2.2.1

**Comment by etagwerker** [comment]
@Whitespace Thanks for the heads up! I just pushed https://github.com/email-spec/email-spec/tree/v2.2.1 with the updated Changelog.md 👍
