### ISSUE TITLE
reset_mailer isn't invoked automatically before each scenario without cucumber

### ISSUE THREAD

**Issue by szymon-przybyl** [email-spec/email-spec#57]
I'm using email-spec with Steak, acceptance tests framework for rspec.

reset_mailer is not invoked before each scenario, we have to do it by hand, but as far as i can see in email_steps generator, there is written that reset_mailer is invoked automatically before each scenario.

**Comment by etagwerker** [comment]
@szymon-przybyl We don't currently have code that supports `steak` but we're definitely open to contributions for this. 

I'm pretty sure it'd look like #180 but using the `steak` api.
