### ISSUE TITLE
Invalid gemspec in rails2 branch

### ISSUE THREAD

**Issue by travisp** [email-spec/email-spec#63]
I get this when checking out the latest from the 0.6-rails2-compat branch:

    email_spec at ... did not have a valid gemspec.
    This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
    The validation message from Rubygems was:
      ["lib/email_spec/#helpers.rb#", "examples/rails3_root", "examples/rails3_root/db", "examples/rails3_root/features",         "examples/rails3_root/features/step_definitions", "examples/rails3_root/features/step_definitions/email_steps.rb", "examples/rails3_root/log", "examples/sinatra/features/step_definitions/email_steps.rb", "examples/sinatra_root", "examples/sinatra_root/features", "examples/sinatra_root/features/step_definitions", "examples/sinatra_root/features/step_definitions/email_steps.rb"] are not file

Commit c692a8211cd9ddec720a seems to have added rails 3 files, and continued the "rsepc" typo

The 0.6.5 tag works, but not 0.6.6, which gives the error "Could not find gem 'rsepc', required by 'email_spec', in any of the sources." Commit 9c418900e8a547bc9d45 has the original typo.

**Comment by etagwerker** [comment]
@travisp Thanks! This is no longer an issue.
